config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
   resources :foods do
    collection do
      get 'search'
    end
  end  
  
  get 'foods/:id/show_image', to: "foods#_show_image"
  get 'subs/:id/show_image', to: "subs#_show_image"

  get 'new_donation', to: "foods#new_donation"
  post 'new_donation', to: "foods#create_donation"

  resources :subs
  get 'subs/:id/push_sub', to: 'subs#push_sub'
  get 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'
  put 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'
  patch 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'

  post 'ideas', to: 'foods#create_idea'
  delete 'ideas/:id', to: 'foods#destroy_idea'
  get 'donation', to: 'foods#custom_donation'

  root "foods#index"

end

app/models/food.rb
class Food < ActiveRecord::Base
	#searchkick
	has_many :joints
	has_many :subs, :through => :joints
  has_one :image, as: :img_duty
	accepts_nested_attributes_for :subs, reject_if: :all_blank, allow_destroy: true
  #accepts_nested_attributes_for :image, reject_if: :all_blank, allow_destroy: true
  # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%") 
    #where(name: "#{query}")
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_filter :check_privileges!, except: [:index, :show, :_show_image, :search, :create_idea, :new_donation, :create_donation, :custom_donation]
  before_filter :admin_value
  before_action :set_food, only: [:show, :_show_image, :edit, :update, :destroy]
  # GET /foods
  # GET /foods.json
  def search
    if params[:search].present?
     @foods = Food.search(params[:search].capitalize).paginate(:page => params[:page], :per_page => 4)
     @subs = Sub.search(params[:search].capitalize).paginate(:page => params[:page], :per_page => 4)
    else
      redirect_to root_path
    end

    #counter for search
    if params[:search].present? || params[:search].present? == false
    @foods_search = Food.all
    @subs_search = Sub.all
#food
    @counters = Hash.new
    @foods_search.each do |c|
      @counters[c.id] = c.counter
    end
    
    @popular_foods = Array.new
    @counters = @counters.sort {|k, v| k[1]<=>v[1]}.reverse
    @counters.each do |id, counter|
      @popular_foods << Food.find(id)
    end
#sub
    @counters_sub = Hash.new
    @subs_search.each do |c|
      @counters_sub[c.id] = c.counter
    end
    
    @popular_subs = Array.new
    @counters_sub = @counters_sub.sort {|k, v| k[1]<=>v[1]}.reverse
    @counters_sub.each do |id, counter|
      @popular_subs << Sub.find(id)
    end
#results
    @popular_foods = @popular_foods[0...3]
    @popular_subs = @popular_subs[0...3]
    end
  end

  def index
    @foods = Food.all #.paginate(:page => params[:page], :per_page => 4)
    @subs = Sub.all #.paginate(:page => params[:page], :per_page => 4)
#food
    # @counters = Hash.new
    # @foods.each do |c|
    #   @counters[c.id] = c.counter
    # end

    # @popular_foods = Array.new
    # if @counters.empty? #add or if @counters.include? nil remove nil record
    #   @counters = nil
    # else
    #   @counters = @counters.keys.sort {|a, b| @counters[b] <=> @counters[a]}
    #   @counters.each do |id, counter|
    #    @popular_foods << Food.find(id)
    #   end
    # end

#sub
    # @counters_sub = Hash.new
    # @subs.each do |c|
    #   @counters_sub[c.id] = c.counter
    # end
    
    # @popular_subs = Array.new
    # if @counters_sub.empty? #add or if @counters.include? nil remove nil record
    #   @counters_sub = nil
    # else
    #   @counters_sub = @counters_sub.keys.sort {|a, b| @counters_sub[b] <=> @counters_sub[a]}
    #   @counters_sub.each do |id, counter|
    #     @popular_subs << Sub.find(id)
    #   end     
    # end

#results
    @popular_foods = Food.where("counter > 1").order(:counter).reverse_order
    @popular_foods = @popular_foods[0...3]
    @popular_subs = Sub.where("counter > 1").order(:counter).reverse_order
    @popular_subs = @popular_subs[0...3]
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    if @food.counter == nil
      @food.update_attribute(:counter, 1)
    else
      @food.update_attribute(:counter, @food.counter+1)
    end
   #send_data(Base64.decode64(@food.image.data), :type => @food.image.mime_type, :filename => @food.image.filename, :disposition => 'inline')
  end

  def _show_image
    send_data(Base64.decode64(@food.image.data), :type => @food.image.mime_type, :filename => @food.image.filename, :disposition => 'inline')
  end
  # GET /foods/new
  def new
    @food = Food.new
    @food.subs.build
    @food.build_image
  end

  # def _index_ideas
  #   @ideas = Idea.all
  # end
  # def _new_idea
  #   @idea = Idea.new
  # end
  def create_idea
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to root_path, notice: 'Idea successfully submitted' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end    
  end

  def destroy_idea
    @idea = Idea.find(params[:id])
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  # GET /foods/1/edit
  def edit
  end

  # def push_sub_name
  #   @sub = 
  #   @food.subs << @sub
  # end
  
  # POST /foods
  # POST /foods.json
  def create
    #@image = Image.create(name: params['food']['image'])
    @food = Food.new(food_params)
    @food.build_image(params['image']) do |t|
      if params['food']['image']['data']
        t.data =      Base64.encode64(params['food']['image']['data'].read)
        t.filename =  params['food']['image']['data'].original_filename
        t.mime_type = params['food']['image']['data'].content_type
      end
    end
    @food.name = @food.name.capitalize
    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    @food.build_image(params['image']) do |t|
      if params['food']['image']['data']
        t.data =      Base64.encode64(params['food']['image']['data'].read)
        t.filename =  params['food']['image']['data'].original_filename
        t.mime_type = params['food']['image']['data'].content_type
      end
    end    
    @food.name = @food.name.capitalize
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    @food.image.destroy
    @j = Joint.where(food_id: @food.id)
    if @j == true
      @j.destroy_all
    end
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_donation
    @amount = flash[:amount]
    @amount = @amount+"00"
    flash.keep(:amount)
  end

  def custom_donation
    if not params[:amount].nil?
      flash[:amount] = params[:amount]
      flash.keep(:amount)
      redirect_to new_donation_path
    end
  end

  def create_donation
    # Amount in cents
    @amount = flash[:amount]
    @amount = @amount+"00"

    customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Smartcrave donation',
    :currency    => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_donation_path
  end

  private

    def check_privileges!
      @admin = User.where(admin: true)
      @god = Array.new
      @admin.each do |a|
        @god.push(a.id)
      end
      if not user_signed_in? 
        redirect_to controller: "devise/registrations", action: "new", notice: "Login or sign up to access content"
      else
        @check = @god.include? current_user.id
        redirect_to root_path, notice: 'You are not an admin' unless @check == true
      end
    end

    def admin_value
      @admin = User.where(admin: true)
      @god = Array.new

      @admin.each do |a|
      @god.push(a.id)
        end

      if user_signed_in?
        @admin = @god.include? current_user.id    
      else
        @admin = false
      end 
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description, :counter, images_attributes: [:name, :data], subs_attributes: [:id, :name, :description, :image, :_destroy])
    end

    def idea_params
      params.require(:idea).permit(:name, :description)
    end

end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_index_ideas.html.erb
<%@ideas = Idea.all%>
<%if @ideas == nil%>
	<p>There are no ideas</p>
<%else%>
	<div class="container-fluid">
		<div class="row center">
			<h2>Ideas submitted by people:</h2>		
		</div>
		<div class="row">
			<% @ideas.each do |idea| %>
				<div class="col-xs-offset-4 pad-bot1">
					<p>Name: <%= idea.name%></p> 
					<p>Description: <%= idea.description%></p>
					<%= link_to '<i class="fa fa-trash fa-3x"></i>'.html_safe, "ideas/#{idea.id}", method: :delete, class: "btn btn-default btn-xs"%>
				</div>
			<%end%>
		</div>	
	</div>
<%end%>

app/views/foods/_new_idea.html.erb
<h2>Submit an Idea !</h2>
<h5>Cravings, cool substitues, recipies ...</h5>
<%@idea = Idea.new%>
<%= form_for @idea do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control1" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control2"%>
  </div>
  <div class="pad-bot">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/foods/_paginate.html.erb
<div class="center apple_pagination">
  <%= will_paginate @foods%>
</div>
<div class="center apple_pagination">
  <%= will_paginate @subs%>
</div>

app/views/foods/_search_index.html.erb
    <div class="brand row center">
        <h4 class="pad-bot2">Smart Crave</h4>
    </div>


    <%= form_tag search_foods_path, method: :get, class: "row center pad-bot", role: "search" do %>
      <%= text_field_tag :search, params[:search], class: "block form-control" %>
      <button>
        <i class="fa fa-search fa-1x"></i>
      </button>
    <% end %>


    <div class="row center">
      <h5>Popular search:</h5>
    </div>

    <div class="row center">
      <div class="popular">
        <ul class="align">
        <% @popular_foods.each do |food|%>
          <li class="align_li"><%= link_to food.name, food%></li>
        <%end%>
        </ul>
        <ul class="align">
        <% @popular_subs.each do |sub|%>
          <li class="align_li"><%= link_to sub.name, sub%></li>
        <%end%>
        </ul>
      </div>
    </div>
    
<div class="row">
<div class="col-xs-12 align_left">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>
</div>

app/views/foods/_show_image.html.erb
<%#image_tag url_for(:controller => "foods_controller", :action => "_show_image", :id => @food.id) %>
 
<!--  send_data(Base64.decode64(@food.image.data), :type => @food.image.mime_type, :filename => @food.image.filename, :disposition => 'inline') -->

app/views/foods/_sub_fields.html.erb
<div class="nested-fields">
<h2>Add a susbstitute</h2>
	<div class="col-xs-offset-4">
	  <%= f.fields_for :image do |img|%>
	    <%= img.label :image %><br>
	    <p class="form-control1">Only upload in edit</p>
	    <%# img.text_field :name, class: "form-control1"%>
	    <%# img.file_field :data %>
	  <%end%>
	</div> 
	<div class="col-xs-offset-4">
		<%= f.label :name %> <br>
		<%= f.text_field :name, class: "form-control1" %>
	</div>

	<div class="col-xs-offset-4">
		<%= f.label :description %> <br>
		<%= f.text_area :description, class: "form-control2" %>
	</div>
	<div class="col-xs-offset-4 btn btn-default">
		<%= link_to_remove_association 'remove sub', f %>
	</div>
</div>

app/views/foods/create_donation.erb
<h2>Thanks, you paid <strong>$<%= @amount.to_i / 100%></strong>!</h2>

app/views/foods/custom_donation.html.erb
<div class="container-fluid brand donate-design">
    <div class="row center">
       <h3>How much do you wish to donate ?</h3>
       <small>Only write round numbers</small>
    </div>
    <div class="row center">

		<%= form_tag donation_path, method: :get, class: "row center brand", role: "search" do %>
		<%= number_field_tag :amount, params[:amount], class: "block form-control" %>
		<button>
			<i class="fa fa-usd"></i>
		</button>
		<% end %>
     
    </div>
  <div class="row center pad-bot2">
    <%= link_to root_path do%>
      <i class="fa fa-arrow-left fa-2x"></i>
    <%end%>
  </div>     
</div>

app/views/foods/edit.html.erb
<h1 class="pad-bot">Editing Food</h1>

<%= render 'form' %>

<div class="center brand">
	<%= link_to 'Show', @food %> |
	<%= link_to 'Back', root_path %>	
</div>

app/views/foods/index.html.erb
<div class="container-fluid background-image">
  <%= render "search_index"%>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 craving center">
      <h3>Latest cravings</h3>
      <div class="row">
        <% @foods.each do |food| %>
          <div class="col-lg-3 col-md-4 col-sm-6 center pad-bot">
          <%#link_to image_tag(food.image.url(:medium), class: "img-rounded"), food%>
          <%=link_to image_tag(url_for(:controller => 'foods', :action => '_show_image', :id => food.id), class: "pad-bot1 img-rounded"), food %>   
          </div>
        <% end %>
      </div>
    </div>
  <%if user_signed_in? %>
    <div class="col-xs-12 sub">
      <%= render "subs/index"%>
    </div>
  <%end%>
  </div>
</div>

<%#render "paginate"%>

app/views/foods/new.html.erb
<h1 class="brand">New Craving</h1>

<%= render 'form' %>

<div class="center">
	<%= link_to root_path do%>
	  <i class="fa fa-arrow-left fa-2x"></i>
	<%end%> 
</div> 

app/views/foods/new_donation.html.erb
<div class="container-fluid brand donate-design">
  <%= form_tag new_donation_path do %>
    <div class="row center">
       <h3>Donate <%= @amount.to_i/100%> $</h3>
    </div>
    <div class="row center">

      <script 
        src="https://checkout.stripe.com/checkout.js" 
        class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="Donation"
        data-amount= "<%= @amount%>"

        ></script>
    </div>
  <% end %>   
  <div class="row center pad-bot2">
    <%= link_to root_path do%>
      <i class="fa fa-arrow-left fa-2x"></i>
    <%end%>
  </div>     
</div>

app/views/foods/search.html.erb
<div class="container-fluid background-image">
  <%= render "search_index"%>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 craving">
        <%if not params[:search].present?%>
<!--           <h3>Cravings:</h3>
        <%#else%> -->
          <h3>Latest Cravings:</h3>
        <%end%>

        <%if @foods.empty? %>
            <div class="row">
              <div class="col-xs-12 brand">
                <div>
                  <p class="text-danger center">No matching cravings for <em><%="#{params[:search]}"%></em> have been found</p>
                  <p class="click_me text-success center" data-toggle="modal" data-target=".bs-example-modal-lg">
                      Propose it ?</br><i class="fa fa-plus-square-o fa-2x"></i></p>
                </div>
              </div>
            </div>
          <%else%>
          <h3 class="text-success">Found cravings:</h3>
          <% @foods.each do |food| %>
            <div class="center">
              <%= link_to food.name, food %>
            </div>
          <% end %>
        <%end%>
    </div>

    <div class="col-sm-6 sub">
      <%= render "subs/index"%>
    </div>
  </div>
</div>

<%= render "paginate"%>

app/views/foods/show.html.erb
<div class="container-fluid pad-top">
  <div class="row center">
    <h2 class="text-success pad-bot2"><%= @food.name %></h2>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-5">
      <div class="row center">
        <%# image_tag @food.image.url(:medium), class: "pad-bot1 img-rounded"%>
        <%=image_tag(url_for(:controller => 'foods', :action => '_show_image'), class: "pad-bot1 img-circle") %>
        <%# render "show_image"%>
      </div>
      <div class="row center">
        <%= link_to root_path do%>
          <i class="fa fa-arrow-left fa-2x"></i>
        <%end%>
        <% if user_signed_in? and @admin == true %>
          | <%= link_to '<i class="fa fa-pencil-square-o fa-2x"></i>'.html_safe, edit_food_path(@food)%> |
          <%= link_to '<i class="fa fa-trash fa-2x"></i>'.html_safe, @food, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>         
      </div>       
      <div class="row center brand">
        <strong>Associated Substitutes:</strong>
          <ul class="ul_show">
            <% @food.subs.each do |sub| %>
             <li><%= link_to sub.name, sub, class: "text-success" %></li>
            <% end %>
          </ul>
      </div> 
    </div>
    <div class="col-xs-12 col-sm-7 pad-bot1 justify lead">
      <%= @food.description %>
    </div>
  </div>
</div>