config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
   resources :foods do
    collection do
      get 'search'
    end
  end  
  
  get 'foods/:id/show_image', to: "foods#_show_image"
  get 'subs/:id/show_image', to: "subs#_show_image"

  get 'new_donation', to: "foods#new_donation"
  post 'new_donation', to: "foods#create_donation"

  resources :subs
  get 'subs/:id/push_sub', to: 'subs#push_sub'
  get 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'
  put 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'
  patch 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'

  post 'ideas', to: 'foods#create_idea'
  delete 'ideas/:id', to: 'foods#destroy_idea'
  get 'donation', to: 'foods#custom_donation'

  root "foods#index"

end

app/models/sub.rb
class Sub < ActiveRecord::Base
	#searchkick
	has_many :joints
	has_many :foods, :through => :joints
  has_one :image, as: :img_duty	
	accepts_nested_attributes_for :foods, reject_if: :all_blank, allow_destroy: true
  #accepts_nested_attributes_for :image, reject_if: :all_blank, allow_destroy: true
	# has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
 #  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%") 
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :check_privileges!, except: [:index, :show, :_show_image]
  before_filter :admin_value
  before_action :set_sub, only: [:show, :edit, :update, :push_sub, :push_sub_to_food, :destroy, :_show_image]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.all
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
    if @sub.counter == nil
      @sub.update_attribute(:counter, 1)
    else
      @sub.update_attribute(:counter, @sub.counter+1)
    end
  end

  def _show_image
    send_data(Base64.decode64(@sub.image.data), :type => @sub.image.mime_type, :filename => @sub.image.filename, :disposition => 'inline')
  end

  # GET /subs/1/edit
  #def edit
  #end
  def push_sub
  end

  def push_sub_to_food
    params[:sub].each do |k, v|
      @food_id = v
    end
    @food = Food.find(@food_id)
    @food.subs << @sub

    redirect_to @food
  end

  def new
    @sub = Sub.new
    #@sub.build_image
  end
  def create
    @sub = Sub.new(sub_params)
    @sub.build_image(params['image']) do |t|
      if params['sub']['image']['data']
        t.data =      Base64.encode64(params['sub']['image']['data'].read)
        t.filename =  params['sub']['image']['data'].original_filename
        t.mime_type = params['sub']['image']['data'].content_type
      end
    end
    @sub.name = @sub.name.capitalize
    respond_to do |format|
      if @sub.save
        format.html { redirect_to @sub, notice: 'Sub was successfully created.' }
        format.json { render :show, status: :created, location: @sub }
      else
        format.html { render :new }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
   @sub.build_image(params['image']) do |t|
      if params['sub']['image']['data']
        t.data =      Base64.encode64(params['sub']['image']['data'].read)
        t.filename =  params['sub']['image']['data'].original_filename
        t.mime_type = params['sub']['image']['data'].content_type
      end
    end    
    @sub.name = @sub.name.capitalize
    respond_to do |format|
      if @sub.update(sub_params)
        format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub }
      else
        format.html { render :edit }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  # def update
  #   respond_to do |format|
  #     if @sub.update(sub_params)
  #       format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @sub }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @sub.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub.destroy
    @sub.image.destroy
    @j = Joint.where(sub_id: @sub.id)
    if @j == true
      @j.destroy_all
    end    
    respond_to do |format|
      format.html { redirect_to subs_url, notice: 'Sub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
      def check_privileges!
      @admin = User.where(admin: true)
      @god = Array.new
      @admin.each do |a|
        @god.push(a.id)
      end
      if not user_signed_in? 
        redirect_to controller: "devise/registrations", action: "new", notice: "Login or sign up to access content"
      else
        @check = @god.include? current_user.id
        redirect_to root_path, notice: 'You are not an admin' unless @check == true
      end
    end

    def admin_value
      @admin = User.where(admin: true)
      @god = Array.new

      @admin.each do |a|
      @god.push(a.id)
        end

      if user_signed_in?
        @admin = @god.include? current_user.id    
      else
        @admin = false
      end 
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_params
      params.require(:sub).permit(:name, :description, :counter, images_attributes: [:name, :data])
    end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<%= form_for @sub, :url => {:action => "push_sub_to_food"} do |f| %>
  <% if @sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub.errors.count, "error") %> prohibited this sub from being saved:</h2>

      <ul>
      <% @sub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1>What food is <%="#{@sub.name}"%> a substitute of?</h1>
  <div class="field">
  <%#select_tag "Food", options_from_collection_for_select(Food.all, "id", "name")%>
    <%=collection_select(:sub, :foods, Food.all, :id, :name)%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subs/_form_sub.html.erb
 <div class="container-fluid">
 <%= form_for @sub, html: {mutlipart: true} do |f| %>
  <% if @sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub.errors.count, "error") %> prohibited this sub from being saved:</h2>
      <ul>
      <% @sub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  
  <div class="row">
      <div class="col-xs-offset-4">
        <%= f.fields_for :image do |img|%>
          <%= img.label :image %><br>
          <%= img.text_field :name, class: "form-control1"%>
          <%= img.file_field :data %>
        <%end%>      
      </div>    
  </div>
  <div class="row">
      <div class="col-xs-offset-4">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control1" %>
      </div>    
  </div>
  <div class="row">
      <div class="col-xs-offset-4">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control2" %>
      </div>   
  </div>
  <div class="row">
      <div class="col-xs-offset-4">
        <%= f.submit class: "btn btn-success"%>
      </div>  
  </div>
<% end %>  
</div>

app/views/subs/_index.html.erb
  <%if not params[:search].present?%>
<!--     <h3>Substitutes:</h3>
  <%#else%> -->
    <h3>Latest substitutes</h3>
  <%end%>

<%if params[:search].present?%>
  <%if @subs.empty? %>
    <div class="row">
      <div class="col-xs-12 brand">
        <div>
          <p class="text-danger center">No matching substitutes for <em><%="#{params[:search]}"%></em> have been found</p>
          <p class="click_me text-success center" data-toggle="modal" data-target=".bs-example-modal-lg">
              Propose it ?</br><i class="fa fa-plus-square-o fa-2x"></i></p>
        </div>
      </div>
    </div>
  <%else%>
  <h3 class="text-success">Found substitutes:</h3>
    <% @subs.each do |sub| %>
      <div class="center">
        <%= link_to sub.name, sub %>
                <% if user_signed_in? and @admin == true%>
          <%= link_to "/subs/#{sub.id}/push_sub" do%>
             <i class="fa fa-plus"></i>
          <%end%>
        <%end%>
      </div>
    <% end %>
  <%end%>
<%else%>

<div class="row">
  <% @subs.each do |sub| %>
    <div class="col-xs-6 col-sm-3 center">
    <%=link_to sub.name, sub%>
    </div>
    <% if user_signed_in? and @admin == true%>
        <div class="col-xs-6 col-sm-9">
        <%= link_to "/subs/#{sub.id}/push_sub" do%>
          <i class="fa fa-plus"></i>
        <%end%>
        </div>
    <%end%>
  <% end %>
</div>

<%end%>

app/views/subs/edit.html.erb
<h1 class="pad-bot">Editing Sub</h1>

<%= render 'form_sub' %>


<div class="center brand">
	<%= link_to 'Show', @sub %> |
	<%= link_to 'Back', root_path %>	
</div>

app/views/subs/new.html.erb
<h1 class="brand">New Substitute</h1>

<%= render 'form_sub' %>

<div class="center">
	<%= link_to root_path do%>
	  <i class="fa fa-arrow-left fa-2x"></i>
	<%end%> 
</div> 

app/views/subs/push_sub.html.erb
<h1>Pushing Sub</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

app/views/subs/show.html.erb
<div class="container-fluid pad-top">
  <div class="row center">
    <h2 class="text-success pad-bot2"><%= @sub.name %></h2>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-5">
      <div class="row center">
        <%=image_tag(url_for(:controller => 'subs', :action => '_show_image'), class: "pad-bot1 img-circle") %>
      </div>
      <div class="row center">
        <%= link_to root_path do%>
          <i class="fa fa-arrow-left fa-2x"></i>
        <%end%>
        <% if user_signed_in? and @admin == true %>
          | <%= link_to '<i class="fa fa-pencil-square-o fa-2x"></i>'.html_safe, edit_sub_path(@sub)%> |
          <%= link_to '<i class="fa fa-trash fa-2x"></i>'.html_safe, @sub, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>         
      </div>      
      <div class="row center brand">
        <strong>Substitute for:</strong>
          <ul class="ul_show">
            <% @sub.foods.each do |food| %>
             <li><%= link_to food.name, food, class: "text-success" %></li>
            <% end %>
          </ul>
      </div>  
    </div>
    <div class="col-xs-12 col-sm-7 pad-bot1 justify lead">
      <%= @sub.description %>
    </div>
  </div>
</div>