config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
   resources :foods do
    collection do
      get 'search'
    end
  end  
  
  get 'foods/:id/show_image', to: "foods#_show_image"
  get 'subs/:id/show_image', to: "subs#_show_image"

  get 'new_donation', to: "foods#new_donation"
  post 'new_donation', to: "foods#create_donation"

  resources :subs
  get 'subs/:id/push_sub', to: 'subs#push_sub'
  get 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'
  put 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'
  patch 'subs/:id/push_sub_to_food', to: 'subs#push_sub_to_food'

  post 'ideas', to: 'foods#create_idea'
  delete 'ideas/:id', to: 'foods#destroy_idea'
  get 'donation', to: 'foods#custom_donation'

  root "foods#index"

end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smartcrave</title>
	<link href='https://fonts.googleapis.com/css?family=Fredericka+the+Great' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Londrina+Sketch' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<div class="container-fluid" id="top-bar">
		<div class="row">
			<%if user_signed_in?%>
				<div class="col-xs-12">
					<ul class="top_ul">
						<% if user_signed_in? and @admin == true %>
						<li class="top_li">
						<%= link_to new_food_path do%>
							<i class="fa fa-fire fa-4x"></i>
						<%end%>
						</li>
						<li class="top_li">
						<%= link_to new_sub_path do%>
							<i class="fa fa-fire-extinguisher fa-4x"></i>
						<%end%>
						</li>
						<li class="top_li click_me" data-toggle="modal" data-target=".bs-example-modal-lg">
								<i class="fa fa-lightbulb-o fa-4x"></i>
						</li>
						<% elsif user_signed_in? and @admin == false || @admin == nil %>
						<li class="top_li">Do not forget to require the admin rights</li>
						<% end %>
<!-- 						<li class="top_li"><strong><%#current_user.email %></strong></li> -->
						<li class="top_li">
						<%= link_to destroy_user_session_path, method: :delete do%>
							<i class="fa fa-sign-out fa-4x"></i>
						<%end%>
						</li>
					</ul>
				</div>
			<%else%>
				<div class="col-sm-offset-6 col-sm-6 col-xs-12">
					<ul class="top_ul">
							<li class="top_li click_me" data-toggle="modal" data-target=".bs-example-modal-lg">
								<i class="fa fa-lightbulb-o fa-4x"></i>
							</li>
							<li class="top_li click_me" data-toggle="modal" data-target=".modal2">
								<i class="fa fa-heart-o fa-4x"></i>
							</li>
							<li class="top_li click_me">
							<%= link_to new_user_session_path do%>
								<i class="fa fa-sign-in fa-4x"></i>
							<%end%>
							</li>
					</ul>
				</div>
			<%end%>
		</div>
	</div>
</header>

<div>
	<%= yield %>
</div>

<!-- Modal -->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
  	<% if user_signed_in? %>
    	<div class="modal-content">
    		<div class="row">
	    		<div class="col-xs-12">
	    			<%= render "foods/index_ideas" %>
	    		</div>
	   		 </div>
		</div>
	<% else %>
		<div class="modal-content">
			<div class="row">
				<div class="col-xs-12 center">
					<%= render "foods/new_idea"%>
				</div>
			</div>
		</div>
	<%end%>
  </div>
</div>
<!-- Modal 2 -->
<div class="fade modal modal2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    	<h5 class="center text-success">3 ways to show us your love !</h5>
    	<div class="row brand pad-love">
    		<div class="col-xs-4 center">    	
    			<a href="mailto:news@smartcrave.org" class="fa fa-envelope fa-5x click_me" style="text-decoration: none;"></a>
    		</div>
    		<div class="col-xs-4 center">
    			<i onclick="myFace()" class="fa fa-facebook fa-5x click_me"></i>
    		</div>
      		<div class="col-xs-4 center">
      			<%= link_to donation_path do%>
      				<i class="fa fa-usd fa-5x click_me"></i>
      			<%end%>
      		</div>
    	</div>
    </div>
  </div>
</div>

<footer>
	<div class="wide_wrapper">
		<div id="logo">
		<div class="pad-left-footer"><i class="fa fa-copyright"></i></div>
		<div class="pad-left-footer">SmartCrave</div>
		<div class="pad-left-footer"><%= Time.now.year %></div>
		</div>
		<nav class="navigation">
		<a href="#" data-toggle="tooltip" data-placement="top" title="FAQ" target="_blank"><i class="fa fa-question fa-2x"></i></a>
		<a onclick="myFace()" data-toggle="tooltip" data-placement="top" title="Be friendly !" target="_blank"><i class="fa fa-facebook-square fa-2x click_me"></i></a>
		<a href="https://monolok.github.io/online" data-toggle="tooltip" data-placement="top" title="Hire me !" target="_blank"><i class="fa fa-github fa-2x"></i></a>
		<a href="#" data-toggle="tooltip" data-placement="top" title="Donate BTC !" target="_blank"><i class="fa fa-btc fa-2x"></i></a>
		<a href="mailto:antoinebe35@gmail.com" data-toggle="tooltip" data-placement="top" title="Say hi !"><i class="fa fa-paper-plane fa-2x"></i></a>
		</nav>
	</div>
</footer>

</body>
</html>